apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: 03-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: config
          configMap:
            name: test-html
      containers:
        - name: app
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: config
            mountPath: "/usr/share/nginx/html"
            readOnly: true