apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: concept-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      # TODO define volume attached to the pod linked with the secret
      containers:
        - name: app
          image: 'app-keystore-secret'
          command: ["java", "Main", "/vault/secrets/keystore.jks"]
          imagePullPolicy: Never
          # TODO mount volume for copying the keystore into the container  
          # TODO add env variable for KEYSTORE_PWD
          resources:
            requests:
              memory: 512Mi
              cpu: "0.5"
            limits:
              cpu: "21"
              memory: 5128Mi

---

# TODO add external secret